[package]
name = "rhy"
version = "0.1.0"
edition = "2021"
description = "A tool for track file state"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
