name: deb

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - uses: actions-rs/toolchain@v1.0.6
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: install compiler
      run: |
        # sudo apt install mingw-w64
        cargo install cargo-deb
 
    - name: Build for deb
      run: |
        cargo deb 

    - name: Upload deb zip
      uses: actions/upload-artifact@v4    
      with:
        name: deb
        path: ./target/debian/*.deb

    - name: Configure coscmd
      env:
        SECRET_ID: ${{ secrets.SECRET_ID }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        BUCKET: ${{ secrets.BUCKET }}
        REGION: ${{ secrets.REGION }}
      run: coscmd config -a $SECRET_ID -s $SECRET_KEY -b $BUCKET -r $REGION
    - name: Upload to cos
      run: |
        coscmd upload -rs ./target/debian/*.deb /deb/rhy --ignore "./.git/*"
        coscmd list /

    
