name: deb

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: install compiler
      run: |
        sudo apt install mingw-w64
        cargo install cargo-deb
 
    - name: Build for deb
      run: |
        cargo deb 

    - name: Upload deb zip
      uses: actions/upload-artifact@v4    
      with:
        name: deb
        path: ./target/debian/*.deb

  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Install coscmd
      run: sudo pip install coscmd

    - uses: actions/download-artifact@v4
      with:
        name: deb
        path: ./target/debian/*.deb

    - name: Configure coscmd
      env:
        SECRET_ID: ${{ secrets.SECRET_ID }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        BUCKET: ${{ secrets.BUCKET }}
        REGION: ${{ secrets.REGION }}
      run: coscmd config -a $SECRET_ID -s $SECRET_KEY -b $BUCKET -r $REGION
    - name: Upload to cos
      run: |
        coscmd upload -rs ./target/debian/*.deb /deb/rhy --ignore "./.git/*"
        coscmd list /

    
